### ISSUE TITLE
termux package

### ISSUE THREAD

**Issue by kawww** [loki-project/session-open-group-server#19]
I like loki very much, and I tried to build a loki public server but it is hard for me to set up vps. I think we really need a playbook about how to set up an public server step by step.

and now I have another idea.

There is an app termux which support run linux server on android. 

https://github.com/termux/termux-packages

Termux support  packages just one step like : pkg i bitcoin

Then everyone could run a bitcoin full node with rpc on android. 

Termux also support ubuntu...https://github.com/Neo-Oli/termux-ubuntu

If loki server have package on it, then local chat or public chat all easy to create and use without vps or domain.

**Comment by neuroscr** [comment]
We now have a proper guide here:
https://docs.loki.network/LokiServices/Messenger/public_channel_setup/

We've also worked on a unified version that will be out soon

**Comment by neuroscr** [comment]
Unified version is out
